---
  language: go
  sudo: false
  go:
    - 1.16.x
  script:
    - export GO111MODULE=on
    - export GOFLAGS=-mod=vendor
    - go mod verify | grep "all modules verified"
    - make binary
    - go vet $(go list ./... | grep -v vendor)
    - test -z "$(gofmt -s -l . | grep -v vendor | tee /dev/stderr)"
    - go test $(go list ./... | grep -v vendor)
